name: 
  workflow_call:
  workflow_dispatch:
jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy: 
      matrix:
        include:
          - os: macos-latest
            commandInstall: ./solipath npm install
            commandTest: ./solipath npm test
          - os: ubuntu-latest
            commandInstall: ./solipath npm install
            commandTest: ./solipath npm test
          - os: windows-latest
            commandInstall: .\solipath npm install
            commandTest: .\solipath npm test
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ${{matrix.commandInstall}}
    - name: Run tests
      run: ${{matrix.commandTest}}